server:
  port: 8083

spring:
  application:
    name: collaboration-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:192.168.232.128:8848}
        namespace: ${NACOS_NAMESPACE:public}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      config:
        server-addr: ${NACOS_SERVER:192.168.232.128:8848}
        namespace: ${NACOS_NAMESPACE:public}
        file-extension: yaml
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
  data:
    redis:
      host: ${REDIS_HOST:192.168.232.128}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:160424}
      database: 0

logging:
  level:
    com.collab: ${LOG_LEVEL:DEBUG}
